# Generated by Django 4.0.10 on 2024-02-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_artical_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='categorys',
            new_name='categories',
        ),
    ]
